/* eslint-disable */

// @generated by scripts/generate_task_quality_types.py; DO NOT EDIT.

export const TASK_QUALITY_WORKFLOW_STATUSES = [
  "draft",
  "analyzing",
  "needs_target_selection",
  "ready",
  "running",
  "validating",
  "reviewing",
  "repairing",
  "recovering",
  "needs_reconciliation",
  "needs_attention",
  "completed",
  "failed",
  "canceled",
  "archived"
] as const;

export const TASK_QUALITY_STATUSES = [
  "pending",
  "checking",
  "pass",
  "fail",
  "unknown",
  "waived"
] as const;

export const TASK_QUALITY_ARTIFACT_STATUSES = [
  "none",
  "uploading",
  "draft",
  "validating",
  "verified",
  "rejected",
  "superseded"
] as const;

export const TASK_QUALITY_BUDGET_STATUSES = [
  "unconfigured",
  "within_budget",
  "warning",
  "exhausted",
  "over_budget",
  "unlimited"
] as const;

export const TASK_QUALITY_BUDGET_MODES = [
  "hard",
  "soft",
  "unlimited"
] as const;

export const TASK_QUALITY_ARCHETYPES = [
  "repo_analysis",
  "code_change",
  "focused_question",
  "document_generation",
  "incident_triage",
  "custom"
] as const;

export const TASK_QUALITY_WORKFLOW_EVENTS = [
  "analysis_requested",
  "cancel_requested",
  "analysis_ready",
  "target_ambiguous",
  "analysis_failed",
  "target_selected",
  "start_requested",
  "candidate_created",
  "runtime_failed",
  "crash_detected",
  "validation_requires_review",
  "repairable_failure",
  "attention_required",
  "fatal_failure",
  "quality_publishable",
  "repaired_candidate_created",
  "repair_exhausted",
  "repair_failed",
  "recovery_succeeded",
  "recovery_uncertain",
  "reconciled_resume",
  "reconciled_fail",
  "resume_requested",
  "repair_requested",
  "archive_requested",
  "retry_requested"
] as const;

export const TASK_QUALITY_WORKFLOW_TRANSITIONS = [
  {
    "from_status": "draft",
    "event": "analysis_requested",
    "to_statuses": [
      "analyzing"
    ],
    "uses_resume_status": false,
    "server_selects_target": false
  },
  {
    "from_status": "draft",
    "event": "cancel_requested",
    "to_statuses": [
      "canceled"
    ],
    "uses_resume_status": false,
    "server_selects_target": false
  },
  {
    "from_status": "analyzing",
    "event": "analysis_ready",
    "to_statuses": [
      "ready"
    ],
    "uses_resume_status": false,
    "server_selects_target": false
  },
  {
    "from_status": "analyzing",
    "event": "target_ambiguous",
    "to_statuses": [
      "needs_target_selection"
    ],
    "uses_resume_status": false,
    "server_selects_target": false
  },
  {
    "from_status": "analyzing",
    "event": "analysis_failed",
    "to_statuses": [
      "draft"
    ],
    "uses_resume_status": false,
    "server_selects_target": false
  },
  {
    "from_status": "analyzing",
    "event": "cancel_requested",
    "to_statuses": [
      "canceled"
    ],
    "uses_resume_status": false,
    "server_selects_target": false
  },
  {
    "from_status": "needs_target_selection",
    "event": "target_selected",
    "to_statuses": [
      "analyzing"
    ],
    "uses_resume_status": false,
    "server_selects_target": false
  },
  {
    "from_status": "needs_target_selection",
    "event": "cancel_requested",
    "to_statuses": [
      "canceled"
    ],
    "uses_resume_status": false,
    "server_selects_target": false
  },
  {
    "from_status": "ready",
    "event": "start_requested",
    "to_statuses": [
      "running"
    ],
    "uses_resume_status": false,
    "server_selects_target": false
  },
  {
    "from_status": "ready",
    "event": "cancel_requested",
    "to_statuses": [
      "canceled"
    ],
    "uses_resume_status": false,
    "server_selects_target": false
  },
  {
    "from_status": "running",
    "event": "candidate_created",
    "to_statuses": [
      "validating"
    ],
    "uses_resume_status": false,
    "server_selects_target": false
  },
  {
    "from_status": "running",
    "event": "attention_required",
    "to_statuses": [
      "needs_attention"
    ],
    "uses_resume_status": false,
    "server_selects_target": false
  },
  {
    "from_status": "running",
    "event": "runtime_failed",
    "to_statuses": [
      "failed"
    ],
    "uses_resume_status": false,
    "server_selects_target": false
  },
  {
    "from_status": "running",
    "event": "crash_detected",
    "to_statuses": [
      "recovering"
    ],
    "uses_resume_status": false,
    "server_selects_target": false
  },
  {
    "from_status": "running",
    "event": "cancel_requested",
    "to_statuses": [
      "canceled"
    ],
    "uses_resume_status": false,
    "server_selects_target": false
  },
  {
    "from_status": "validating",
    "event": "validation_requires_review",
    "to_statuses": [
      "reviewing"
    ],
    "uses_resume_status": false,
    "server_selects_target": false
  },
  {
    "from_status": "validating",
    "event": "repairable_failure",
    "to_statuses": [
      "repairing"
    ],
    "uses_resume_status": false,
    "server_selects_target": false
  },
  {
    "from_status": "validating",
    "event": "attention_required",
    "to_statuses": [
      "needs_attention"
    ],
    "uses_resume_status": false,
    "server_selects_target": false
  },
  {
    "from_status": "validating",
    "event": "fatal_failure",
    "to_statuses": [
      "failed"
    ],
    "uses_resume_status": false,
    "server_selects_target": false
  },
  {
    "from_status": "validating",
    "event": "crash_detected",
    "to_statuses": [
      "recovering"
    ],
    "uses_resume_status": false,
    "server_selects_target": false
  },
  {
    "from_status": "reviewing",
    "event": "quality_publishable",
    "to_statuses": [
      "completed"
    ],
    "uses_resume_status": false,
    "server_selects_target": false
  },
  {
    "from_status": "reviewing",
    "event": "repairable_failure",
    "to_statuses": [
      "repairing"
    ],
    "uses_resume_status": false,
    "server_selects_target": false
  },
  {
    "from_status": "reviewing",
    "event": "attention_required",
    "to_statuses": [
      "needs_attention"
    ],
    "uses_resume_status": false,
    "server_selects_target": false
  },
  {
    "from_status": "reviewing",
    "event": "fatal_failure",
    "to_statuses": [
      "failed"
    ],
    "uses_resume_status": false,
    "server_selects_target": false
  },
  {
    "from_status": "reviewing",
    "event": "crash_detected",
    "to_statuses": [
      "recovering"
    ],
    "uses_resume_status": false,
    "server_selects_target": false
  },
  {
    "from_status": "repairing",
    "event": "repaired_candidate_created",
    "to_statuses": [
      "validating"
    ],
    "uses_resume_status": false,
    "server_selects_target": false
  },
  {
    "from_status": "repairing",
    "event": "repair_exhausted",
    "to_statuses": [
      "needs_attention"
    ],
    "uses_resume_status": false,
    "server_selects_target": false
  },
  {
    "from_status": "repairing",
    "event": "repair_failed",
    "to_statuses": [
      "failed"
    ],
    "uses_resume_status": false,
    "server_selects_target": false
  },
  {
    "from_status": "repairing",
    "event": "crash_detected",
    "to_statuses": [
      "recovering"
    ],
    "uses_resume_status": false,
    "server_selects_target": false
  },
  {
    "from_status": "recovering",
    "event": "recovery_succeeded",
    "to_statuses": [
      "running",
      "validating",
      "reviewing",
      "repairing"
    ],
    "uses_resume_status": true,
    "server_selects_target": false
  },
  {
    "from_status": "recovering",
    "event": "recovery_uncertain",
    "to_statuses": [
      "needs_reconciliation"
    ],
    "uses_resume_status": false,
    "server_selects_target": false
  },
  {
    "from_status": "needs_reconciliation",
    "event": "reconciled_resume",
    "to_statuses": [
      "running",
      "validating",
      "reviewing",
      "repairing"
    ],
    "uses_resume_status": true,
    "server_selects_target": false
  },
  {
    "from_status": "needs_reconciliation",
    "event": "reconciled_fail",
    "to_statuses": [
      "failed"
    ],
    "uses_resume_status": false,
    "server_selects_target": false
  },
  {
    "from_status": "needs_reconciliation",
    "event": "cancel_requested",
    "to_statuses": [
      "canceled"
    ],
    "uses_resume_status": false,
    "server_selects_target": false
  },
  {
    "from_status": "needs_attention",
    "event": "resume_requested",
    "to_statuses": [
      "ready",
      "running",
      "validating",
      "repairing"
    ],
    "uses_resume_status": false,
    "server_selects_target": true
  },
  {
    "from_status": "needs_attention",
    "event": "cancel_requested",
    "to_statuses": [
      "canceled"
    ],
    "uses_resume_status": false,
    "server_selects_target": false
  },
  {
    "from_status": "completed",
    "event": "repair_requested",
    "to_statuses": [
      "repairing"
    ],
    "uses_resume_status": false,
    "server_selects_target": false
  },
  {
    "from_status": "completed",
    "event": "archive_requested",
    "to_statuses": [
      "archived"
    ],
    "uses_resume_status": false,
    "server_selects_target": false
  },
  {
    "from_status": "failed",
    "event": "retry_requested",
    "to_statuses": [
      "ready"
    ],
    "uses_resume_status": false,
    "server_selects_target": false
  },
  {
    "from_status": "failed",
    "event": "archive_requested",
    "to_statuses": [
      "archived"
    ],
    "uses_resume_status": false,
    "server_selects_target": false
  },
  {
    "from_status": "canceled",
    "event": "archive_requested",
    "to_statuses": [
      "archived"
    ],
    "uses_resume_status": false,
    "server_selects_target": false
  }
] as const;

export type TaskQualityWorkflowStatus = (typeof TASK_QUALITY_WORKFLOW_STATUSES)[number];

export type TaskQualityStatus = (typeof TASK_QUALITY_STATUSES)[number];

export type TaskQualityArtifactStatus = (typeof TASK_QUALITY_ARTIFACT_STATUSES)[number];

export type TaskQualityBudgetStatus = (typeof TASK_QUALITY_BUDGET_STATUSES)[number];

export type TaskQualityBudgetMode = (typeof TASK_QUALITY_BUDGET_MODES)[number];

export type TaskQualityArchetype = (typeof TASK_QUALITY_ARCHETYPES)[number];

export type TaskQualityWorkflowEvent = (typeof TASK_QUALITY_WORKFLOW_EVENTS)[number];

export type TaskQualityWorkflowTransition = (typeof TASK_QUALITY_WORKFLOW_TRANSITIONS)[number];
