"""Generate the GUI Task Quality enum snapshot from canonical Python models."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from coworker.orchestration.quality.state_machine import task_quality_schema_snapshot  # noqa: E402


TARGET = ROOT / "surfaces/gui/src/features/orchestration/taskQuality.generated.ts"


def _constant(name: str, value: Any) -> str:
    return f"export const {name} = {json.dumps(value, indent=2, ensure_ascii=False)} as const;"


def render() -> str:
    value = task_quality_schema_snapshot()
    blocks = [
        "/* eslint-disable */",
        "// @generated by scripts/generate_task_quality_types.py; DO NOT EDIT.",
        _constant("TASK_QUALITY_WORKFLOW_STATUSES", value["workflow_statuses"]),
        _constant("TASK_QUALITY_STATUSES", value["quality_statuses"]),
        _constant("TASK_QUALITY_ARTIFACT_STATUSES", value["artifact_statuses"]),
        _constant("TASK_QUALITY_BUDGET_STATUSES", value["budget_statuses"]),
        _constant("TASK_QUALITY_BUDGET_MODES", value["budget_modes"]),
        _constant("TASK_QUALITY_ARCHETYPES", value["archetypes"]),
        _constant("TASK_QUALITY_WORKFLOW_EVENTS", value["workflow_events"]),
        _constant("TASK_QUALITY_WORKFLOW_TRANSITIONS", value["workflow_transitions"]),
        "export type TaskQualityWorkflowStatus = (typeof TASK_QUALITY_WORKFLOW_STATUSES)[number];",
        "export type TaskQualityStatus = (typeof TASK_QUALITY_STATUSES)[number];",
        "export type TaskQualityArtifactStatus = (typeof TASK_QUALITY_ARTIFACT_STATUSES)[number];",
        "export type TaskQualityBudgetStatus = (typeof TASK_QUALITY_BUDGET_STATUSES)[number];",
        "export type TaskQualityBudgetMode = (typeof TASK_QUALITY_BUDGET_MODES)[number];",
        "export type TaskQualityArchetype = (typeof TASK_QUALITY_ARCHETYPES)[number];",
        "export type TaskQualityWorkflowEvent = (typeof TASK_QUALITY_WORKFLOW_EVENTS)[number];",
        "export type TaskQualityWorkflowTransition = (typeof TASK_QUALITY_WORKFLOW_TRANSITIONS)[number];",
    ]
    return "\n\n".join(blocks) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if the checked-in generated file differs from Python",
    )
    args = parser.parse_args()
    expected = render()
    if args.check:
        if not TARGET.exists() or TARGET.read_text(encoding="utf-8") != expected:
            print(f"Task Quality generated types are stale: {TARGET}", file=sys.stderr)
            return 1
        print(f"Task Quality generated types are current: {TARGET}")
        return 0
    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(expected, encoding="utf-8", newline="\n")
    print(f"Generated {TARGET}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
